### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by torleif** [tualo/tualo-git-context#21]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.6.10
### Stack Trace

Uncaught TypeError: Cannot read property 'getAttribute' of null

```
At C:\Users\torleifw\.atom\packages\tualo-git-context\lib\tualo-git-context.coffee:55

TypeError: Cannot read property 'getAttribute' of null
  at Object.atom.contextMenu.add..tree-view.shouldDisplay (C:\Users\torleifw\.atom\packages\tualo-git-context\lib\tualo-git-context.coffee:55:28)
  at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (C:\Users\torleifw\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:108:25)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\torleifw\AppData\Local\atom\app-1.0.0\resources\app.asar\src\context-menu-manager.js:166:27)
  at HTMLDocument.<anonymous> (C:\Users\torleifw\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:150:33)
  at HTMLDocument.handler (C:\Users\torleifw\AppData\Local\atom\app-1.0.0\resources\app.asar\src\space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (C:\Users\torleifw\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4681:9)
  at HTMLDocument.elemData.handle (C:\Users\torleifw\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\space-pen\vendor\jquery.js:4359:46)

```
### Commands

```
     -1:20.2.0 atomatigit:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.3
autocomplete-php, v0.3.6
linter-csslint, v0.0.14
linter-jscs, v1.12.0
linter-php, v0.0.15
minimap, v4.10.0
minimap-git-diff, v4.1.3
nuclide-diff-view, v0.0.22
silverstripe-bundle, v0.1.0
silverstripe-syntax-and-snippets, v0.4.0
tree-view-git-status, v0.1.1
tualo-git-context, v0.6.10

# Dev
No dev packages
```

**Comment by torleif** [comment]
right click project

**Comment by thomashoffmann1979** [comment]
Hi, i can't reproduce the error. But i have found an unchecked variable in the script. I have fixed that in version 0.6.11. Hopefully this will fix the error.

**Comment by torleif** [comment]
thanks for fixing the other issue

sadly this one is still happening with 6.11 . it seems to get triggered when I right click the root folder of the project.
